# The URL the site will be built for
base_url = "https://alxndr.github.io/kglw-site" # TODO change to kglw.net

theme = "terminimal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]

logo_text = "KGLW.net"
copyright_html = "brought to you by the fans of Gizzard @ KGLW.net"

accent_color = "green"
favicon = "/logo.png"
favicon_mimetype = "image/png"

default_language = "en"

menu_items = [
  # each of these is optional, name and url are required
  # $BASE_URL is going to be substituted by base_url from configuration

  {name = "setlists", url = "$BASE_URL/shows"},
  {name = "releases", url = "$BASE_URL/gizzverse-guide"},
  {name = "band info", url = "$BASE_URL/band-bio"},
  {name = "blog", url = "javascript:alert('coming soon')"},

  # # set newtab to true to make the link open in new tab
  {name = "twitter", url = "https://twitter.com/kglw_net", newtab = true},
  {name = "github", url = "https://github.com/kglw-dot-net", newtab = true},
]
